name: Output something

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write

jobs:
  output_something:
    runs-on: ubuntu-latest

    steps:
      - name: Write the summary.md
        shell: bash
        run: |
          REPORT_FILE=$(mktemp -t summary.md.XXXXX)
          echo "REPORT_FILE=$REPORT_FILE" >> $GITHUB_ENV
          cat >> $REPORT_FILE << 'ENDOFREPORT'
          ## Headline
          ENDOFREPORT

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: 1
          body: |
            This is a multi-line test comment
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]

            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+2'