name: Dynamic Matrix Example

on: push

jobs:
  staging_build:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.compute.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Compute matrix
        id: compute
        run: python scripts/script.py

  staging_deploy:
    needs: [staging_build]
    runs-on: ubuntu-latest
    environment: staging
    strategy:
      matrix:
        service: ${{ fromJson(needs.staging_build.outputs.matrix) }}
    
    steps:
      - name: Matrix out
        run: |
         echo "Testing service: ${{ matrix.service }}"

  production_build:
    runs-on: ubuntu-latest
    environment: production
    outputs:
      matrix: ${{ steps.compute.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Compute matrix
        id: compute
        run: python scripts/script.py
    
  production_deploy:
    runs-on: ubuntu-latest
    needs: [production_build]
    steps:
      - name: Matrix out
        run: |
          echo "Testing service: ${{ matrix.service }}"
